### ISSUE TITLE
Latest TE 5.5.1.33 appears to have broke removing induction smelter recipes (possibly more) with CraftTweaker

### ISSUE THREAD

**Issue by tgstyle** [jaredlll08/ModTweaker#692] opened 2018-10-02 20:42 UTC
#### Issue Description:
I have tried my script to remove them both ways even in succession. There is no error in the CT log, it even shows it removed them both ways, yet they still process in the machine and show in JEI.

#### What happens:
Nothing is removed

#### What you expected to happen:
Items in the script to be removed

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will 
https://gist.github.com/tgstyle/d95356169932fbc250e023835b56c643

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2765
- Crafttweaker:  4.1.9
- ModTweaker: 4.0.14 and 4.0.13
- MTLib: 3.0.5

https://github.com/CoFH/Feedback/issues/1308

**Comment by tgstyle** [comment] 2018-10-08 19:29
With the latest TE 5.5.2.39 and this PR in a custom build, plus having to put wildcards for meta where previously was not needed, seems to have fixed it.
https://github.com/jaredlll08/ModTweaker/pull/686

**Comment by noobanidus** [comment] 2018-10-10 07:38
It does appear to be something to do with the conversion of ItemStacks into the comparable ones that are used by CoFH. As in, the issue is that getRecipe does a lot of work to find the right combination of comparable item stacks, but removeRecipe doesn't.

**Comment by noobanidus** [comment] 2018-10-11 00:35
I believe this is an issue with ThermalExpansion and not ModTweaker. I've opened an issue with CoFH, and hopefully it can be resolved from that end.

**Comment by jaredlll08** [comment] 2018-10-19 13:41
This was either fixed by a PR, or I can't reproduce.

**Closed as completed by jaredlll08** 2018-10-19 13:41 UTC
