### ISSUE TITLE
Thermal Enchanter

### ISSUE THREAD

**Issue by Fortist** [jaredlll08/ModTweaker#632] opened 2018-04-29 18:53 UTC
Adding new Enchants to The Arcane Enchanter machine messes with the already in place enchants.

**Comment by KingLemming** [comment] 2018-04-30 20:18
What version of TE are you using?

**Comment by Fortist** [comment] 2018-05-03 00:32
@KingLemming The latest one, which is.... 5.4.2.27.
It may be an enchant mod I have, but Ill explain it better since it seems to actually do nothing but mess with JEI.
When adding enchants to the AE, certain "out of the box" enchants mess up in the way that it shows a different enchant output with an input, like Wither skulls make "Advanced Lure" or whatever.
However, putting in the skull will still yield Vorpal. (At least I think, I made multishot and punch when those had a messed up recipe, however)
I also noticed that each recipe is listed three times, and One or two would be messed up output, but the last one would be the correct output.

This also happens to happen to anvil enchant creating (Rocky core?) So im thinking it might be some shenanigans with the enchant mod Im using.

**Comment by KingLemming** [comment] 2018-05-03 02:53
This is actually a JEI issue...sort of. It's caused by a quirk with how Minecraft still uses integer values for enchantments, as opposed to literally everything else which uses ResourceLocations.

**Comment by Fortist** [comment] 2018-05-03 09:25
Alright, I'll play around some more with it and see if there is an actual issue down the line, since it seems like a pure cosmetic thing.

**Comment by jaredlll08** [comment] 2018-05-03 09:29
Going to close this since it isn't modtweaker

**Closed as completed by jaredlll08** 2018-05-03 09:29 UTC
