### ISSUE TITLE
1.11 Crashlog on launch without Forestry.

### ISSUE THREAD

**Issue by Rixius** [jaredlll08/ModTweaker#489] opened 2017-06-09 05:10 UTC
#### Issue Description:
Launching a modpack without Forestry causes a crash during pre-initialization. Adding forestry 1.11.2-5.3.4.101 causes the game to boot as expected.

#### What happens:
Crashes during Phase 2/7 of startup.

#### What you expected to happen:
Successfully launch the game.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
None

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
The file is empty.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2315
- Crafttweaker: 1.11.2-3.0.25
- ModTweaker: 3.0.0
- MTLib: 2.0.3

#### Your most recent log file where the issue was present: 
https://gist.github.com/Rixius/203dc4623fe720118c9f509b1fd81488

**Comment by SnowShock35** [comment] 2017-06-09 06:52
Can Confirm, the issue is definitely crashing without Forestry's presence.

**Comment by Zarepheth** [comment] 2017-06-10 04:15
I think I reported this problem for the wrong mod...
https://github.com/jaredlll08/CraftTweaker/issues/230

**Comment by jaredlll08** [comment] 2017-06-10 14:47
fixed in latest release

**Closed by jaredlll08** 2017-06-10 14:47 UTC
