### ISSUE TITLE
Forestry Carpenter support not functioning

### ISSUE THREAD

**Issue by KnightMiner** [jaredlll08/ModTweaker#404] opened 2016-12-25 02:38 UTC
Using Attempting to add a simple carpenter recipe outputs the following error:

> Error executing *script*.zs: modtweaker/mods/forestry/recipes/DescriptiveRecipe

And does not function. Now, I do not entirely understand how MineTweakers nor Forestrys API's work, but I'm pretty sure at least part of the issue would be the fact that [the ingredients parameter is never passed into the recipe](https://github.com/jaredlll08/ModTweaker/blob/master/src/main/java/modtweaker/mods/forestry/handlers/Carpenter.java#L39-L44).

As is likely relevant:
* CraftTweaker: 1.10.2-3.0.15
* ModTweaker: 2.0.7
* Forestry: 5.2.16.346

**Comment by jaredlll08** [comment] 2016-12-25 09:42
Duplicate of: #393

**Closed by jaredlll08** 2016-12-25 09:42 UTC
