### ISSUE TITLE
Cannot Add Fuels To Smeltery (1.10.2)

### ISSUE THREAD

**Issue by Darkosto** [jaredlll08/ModTweaker#372] opened 2016-10-02 20:42 UTC
Hey Jared,

I'm getting the same error for trying to add fuels to a smeltery that I was getting for the basin recipes. Have I added them incorrectly? :)

Modtweaker Version: 2.0.4
Minetweaker Version: 3.0.11
Minecraft: 1.10.2

Script:
mods.tconstruct.Smeltery.addFuel(<liquid:fire_water>, 64, 64);

Log:
http://pastebin.com/zAGw4cLS

Thank you very much for looking into this! :D

**Comment by jaredlll08** [comment] 2016-10-02 20:45
Smeltery stuff isn't implemented in the current version, I couldn't find where to do it when I ported the mod, so I had to leave it out, it will be in hopefully the next update

**Comment by jaredlll08** [comment] 2016-10-02 20:47
well actually, I'm wrong, it is implemented, but I couldn't find where to set the temperature of it, so just use 
```
mods.tconstruct.Smeltery.addFuel(liquid:fire_water);
```

**Comment by WolfieWaffle** [comment] 2016-10-12 01:51
The problem is that the default temperature seems to be 300, too low to melt almost anything. I'll look through this Git and see if I can find the problem, I probably won't since I'm not too good at Java but I'll post here if I find anything.

**Comment by jaredlll08** [comment] 2016-10-12 10:52
This is a problem with TiC, there is no method to change the temp, all I found was hints at a block that will heat up the smeltery, but that was just in code, I havn't actually played TiC 1.10.2

**Closed by jaredlll08** 2016-10-12 10:52 UTC

**Comment by Yulife** [comment] 2016-10-12 12:57
Doesn't TiC pull the temperature from the stats of the liquid?

**Comment by WolfieWaffle** [comment] 2016-10-12 15:57
hm, in that case that is a problem with my liquid I'm using (creosote oil from railcraft). But I want to use it as fuel  for early game, as lava is difficult to find. Is this going to require some sort of addon mod instead?

One workaround is to decrease the melting temperature of all the items you want to be able to smelt with that fuel, but it's not ideal. That's what I will be doing for now though.
