### ISSUE TITLE
[1.10.2] Cannot add Smeltery fuel sources to Tinker's Construct

### ISSUE THREAD

**Issue by Compegen** [jaredlll08/ModTweaker#476] opened 2017-04-25 02:07 UTC
#### Issue Description:
When adding a fuel source to Tinker's the arguments that are supposed to be given are returned as invalid (Wiki says you need FluidStack, Temperature, Ticks).

When adding fuel source with the arguments your code calls for (Just FluidStack), it saves and runs correctly but is nonfunctional.

#### What happens:
Fuel is not used, and items display as not having enough heat.

#### What you expected to happen:
Fuel to be used, and items beginning to smelt.

[Script.](https://pastebin.com/7Es2z3DP)

[Minetweaker.log](https://pastebin.com/P4igpJZa)

____
#### Affected Versions
- Minecraft: `1.10.2`
- Forge: `1.10.2-12.18.3.2281`
- Crafttweaker: `1.10.2-3.0.24`
- ModTweaker: `2.0.11`
- MTLib: `1.0.2`

![2017-04-24_21 07 23](https://cloud.githubusercontent.com/assets/8009507/25365969/0ba50f2e-2932-11e7-9ed3-5e3c5c0b1e0f.png)

**Comment by jaredlll08** [comment] 2017-04-25 06:25
Duplicate of https://github.com/jaredlll08/ModTweaker/issues/439

**Closed by jaredlll08** 2017-04-25 06:25 UTC
